# Generated by Django 5.1.3 on 2024-12-03 21:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fitcom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_workout_programs',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='fitcom_app.usercustomworkoutprogram'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_program_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='dailyuserprogress',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 12, 3, 21, 34, 49, 138332, tzinfo=datetime.timezone.utc)),
        ),
    ]
