# Generated by Django 5.1.4 on 2024-12-17 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_dailyuserprogress_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserprogress',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 12, 17, 15, 59, 29, 759522, tzinfo=datetime.timezone.utc)),
        ),
    ]
