# Generated by Django 5.1.4 on 2024-12-17 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitcom_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='is_admin_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usercustomworkoutprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
