# Generated by Django 5.1.3 on 2024-11-21 23:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitcom_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="id",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="exercise_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
