# Generated by Django 5.1.3 on 2024-11-25 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitcom_app', '0003_workoutprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='schedule',
            field=models.ManyToManyField(to='fitcom_app.exercise'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
