# Generated by Django 5.1.3 on 2024-12-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fitcom_app', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_workout_programs',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='fitcom_app.usercustomworkoutprogram'),
        ),
    ]
