# Generated by Django 5.1.3 on 2024-11-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
