# Generated by Django 5.1.3 on 2024-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fitcom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_workout_programs',
            field=models.ManyToManyField(blank=True, to='fitcom_app.workoutprogram'),
        ),
    ]
