# Generated by Django 5.1.3 on 2024-12-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_saved_workout_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='userLevel',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary: little or no exercise'), ('Light', 'Light: exercise 1-3 times/week'), ('Moderate', 'Moderate: exercise 4-5 times/week'), ('Active', 'Active: daily exercise or intense exercise 3-4 times/week'), ('Very Active', 'Very Active: intense exercise 6-7 times/week'), ('Extra Active', 'Extra Active: very intense exercise daily, or physical job')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(),
        ),
    ]
