# Generated by Django 5.1.3 on 2024-12-04 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_dailyuserprogress_date_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserprogress',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 12, 4, 9, 24, 34, 994061, tzinfo=datetime.timezone.utc)),
        ),
    ]
