name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install backend dependencies
      run: |
        python -m venv venv
        . ./venv/bin/activate
        pip install -r requirements.txt
        cd backend

    - name: Run backend tests
      working-directory: ./backend
      run: |
        . ../venv/bin/activate
        python manage.py test

  # frontend:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Set up Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '14.x'  # Specify the Node.js version you need

  #   - name: Install front-end dependencies
  #     run: |
  #       cd frontend/fitcom_app
  #       npm install

  #   - name: Install Jest
  #     run: |
  #       cd frontend/fitcom_app
  #       npm install jest --save-dev

  #   - name: Run front-end tests
  #     run: |
  #       cd frontend/fitcom_app
  #       npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [backend]
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        # Add your deployment script here
        echo "Deploying the application..."
